%% test_cross_validate.m  -- Cross-validate octave-rf against scikit-rf / py370
%%
%% Loads reference .mat vectors generated by
%%   validation/cross_validate_octave_rf.py
%% and compares every octave-rf function against the reference.
%%
%% Usage (from octave-rf/ directory):
%%   octave-cli --no-gui -q --path inst test/test_cross_validate.m
%%
%% Tolerances:
%%   tol_fp  = 1e-11  -- parameter conversions (s2t, s2z, s2y, s2abcd, s2h, s2g)
%%   tol_net = 1e-10  -- network operations (cascade, deembed)
%%   tol_mm  = 1e-11  -- mixed-mode conversions

addpath (fullfile (fileparts (mfilename ('fullpath')), '..', 'inst'));

TVEC = fullfile (fileparts (mfilename ('fullpath')), 'testvectors');

tol_fp  = 1e-11;
tol_net = 1e-10;
tol_mm  = 1e-11;

pass = 0;  fail = 0;

function ok = chk (tag, observed, ref, tol)
  d = max (abs (observed(:) - ref(:)));
  if d <= tol
    printf ('  PASS  %-34s  max|diff| = %.2e\n', tag, d);
    ok = true;
  else
    printf ('  FAIL  %-34s  max|diff| = %.2e  (tol=%.0e)\n', tag, d, tol);
    ok = false;
  end
endfunction

%% =============================================================================
printf ('\n--- 1. 2-port parameter conversions (pcb_stripline_119mm) ---\n');
v = load (fullfile (TVEC, 'conversion_2port.mat'));
S = v.S2;  freq = v.freq2(:);

ok  = chk ('s2t vs skrf',        s2t(S),          v.T2_ref, tol_fp);
ok &= chk ('t2s round-trip',     t2s(s2t(S)),     S,        tol_fp);
ok &= chk ('s2z vs skrf',        s2z(S),          v.Z2_ref, tol_fp);
ok &= chk ('z2s round-trip',     z2s(s2z(S)),     S,        tol_fp);
ok &= chk ('s2y vs skrf',        s2y(S),          v.Y2_ref, tol_fp);
ok &= chk ('y2s round-trip',     y2s(s2y(S)),     S,        tol_fp);
ok &= chk ('s2abcd vs skrf',     s2abcd(S),       v.A2_ref, tol_fp);
ok &= chk ('abcd2s round-trip',  abcd2s(s2abcd(S)), S,      tol_fp);
ok &= chk ('s2h vs skrf(Z)',     s2h(S),          v.H2_ref, tol_fp);
ok &= chk ('h2s round-trip',     h2s(s2h(S)),     S,        tol_fp);
ok &= chk ('s2g vs skrf(inv H)', s2g(S),          v.G2_ref, tol_net); %% G=inv(H): inversion amplifies conditioning errors; use tol_net
ok &= chk ('g2s round-trip',     g2s(s2g(S)),     S,        tol_fp);
if ok; pass++; else fail++; end

%% =============================================================================
printf ('\n--- 2. 4-port Z and Y parameters (CABLE1_RX_pair) ---\n');
v4 = load (fullfile (TVEC, 'conversion_4port.mat'));
S4 = v4.S4;

ok  = chk ('s2z 4-port vs skrf', s2z(S4),        v4.Z4_ref, tol_fp);
ok &= chk ('z2s 4-port r-trip',  z2s(s2z(S4)),   S4,        tol_fp);
ok &= chk ('s2y 4-port vs skrf', s2y(S4),        v4.Y4_ref, tol_fp);
ok &= chk ('y2s 4-port r-trip',  y2s(s2y(S4)),   S4,        tol_fp);
if ok; pass++; else fail++; end

%% =============================================================================
printf ('\n--- 3. cascadesparams (case_01_2xThru ** case_01_2xThru) ---\n');
vc = load (fullfile (TVEC, 'cascade.mat'));
S2x = vc.S2x;

ok = chk ('cascadesparams vs skrf', cascadesparams(S2x, S2x), vc.Scas_ref, tol_net);
if ok; pass++; else fail++; end

%% =============================================================================
printf ('\n--- 4. embedsparams (identity fixture round-trip) ---\n');
K = size (S2x, 3);
thru = zeros (2, 2, K);  thru(1,2,:) = 1;  thru(2,1,:) = 1;
Sembed = embedsparams (thru, S2x, thru);
Srt    = deembedsparams (Sembed, thru, thru);
ok = chk ('embed/deembed identity fixtures', Srt, S2x, tol_net);
if ok; pass++; else fail++; end

%% =============================================================================
printf ('\n--- 5. deembedsparams (pcb_238 from py370 NZC fixtures) ---\n');
vd = load (fullfile (TVEC, 'deembed.mat'));
Sdut = deembedsparams (vd.S_cascade, vd.S_side1, vd.S_side2);
ok  = chk ('deembed vs py370',  Sdut, vd.S_dut_ref,  tol_net);
ok &= chk ('deembed vs scikit-rf', Sdut, vd.S_dut_skrf, tol_net);
if ok; pass++; else fail++; end

%% =============================================================================
printf ('\n--- 6. renormsparams (pcb_119: 50 Ohm -> 75 Ohm) ---\n');
vr = load (fullfile (TVEC, 'renorm.mat'));
S_r75 = renormsparams (vr.S2, 75, 50);
S_rt  = renormsparams (S_r75, 50, 75);   %% round-trip back to 50 Ohm
ok  = chk ('renorm 50->75 vs skrf',  S_r75, vr.S_renorm75_ref, tol_fp);
ok &= chk ('renorm round-trip',      S_rt,  vr.S2,             tol_fp);
if ok; pass++; else fail++; end

%% =============================================================================
printf ('\n--- 7. mixed-mode: s2smm / s2sdd / s2scc / smm2s ---\n');
%% portorder=[1,2,3,4]: adjacent pairs -- pair1=(1,2), pair2=(3,4)
%% Matches py370 port_order=2 and scikit-rf se2gmm(p=2)
vm = load (fullfile (TVEC, 'mixed_mode.mat'));
S4m = vm.S4;
po = [1 2 3 4];   %% adjacent-pair convention

Smm  = s2smm (S4m, po);
Sdd  = s2sdd (S4m, po);
Scc  = s2scc (S4m, po);
S4rt = smm2s (Smm(1:2,1:2,:), Smm(1:2,3:4,:), ...
              Smm(3:4,1:2,:), Smm(3:4,3:4,:), po);

ok  = chk ('s2smm vs py370',      Smm,  vm.Smm_ref,  tol_mm);
ok &= chk ('s2smm vs scikit-rf',  Smm,  vm.Smm_skrf, tol_mm);
ok &= chk ('s2sdd vs py370',      Sdd,  vm.Sdd_ref,  tol_mm);
ok &= chk ('s2scc vs py370',      Scc,  vm.Scc_ref,  tol_mm);
ok &= chk ('smm2s round-trip',    S4rt, S4m,         tol_mm);
if ok; pass++; else fail++; end

%% =============================================================================
printf ('\n--- 8. snp2smp (2-port swap and round-trip) ---\n');
vp = load (fullfile (TVEC, 'portreorder.mat'));
S2p = vp.S2;
Ssw  = snp2smp (S2p, [2 1]);    %% swap ports
Srt2 = snp2smp (Ssw, [2 1]);    %% undo swap
ok  = chk ('snp2smp swap vs ref', Ssw,  vp.S_swapped, 1e-14);
ok &= chk ('snp2smp round-trip',  Srt2, S2p,           1e-14);
if ok; pass++; else fail++; end

%% =============================================================================
printf ('\n--- 9. sparameters Form 3 renorm consistency ---\n');
s50 = sparameters (S2p, freq, 50);
s75 = sparameters (s50, 75);      %% Form 3: renormalize object to 75 Ohm
ok = chk ('sparameters Form3 vs renormsparams', s75.Parameters, ...
          renormsparams(S2p, 75, 50), tol_fp);
if ok; pass++; else fail++; end

%% =============================================================================
printf ('\n');
printf ('=== SUMMARY ===\n');
printf ('  Groups passed: %d\n', pass);
printf ('  Groups failed: %d\n', fail);
if fail == 0
  printf ('  All octave-rf functions agree with scikit-rf / py370 references.\n');
else
  printf ('  *** %d group(s) exceeded tolerance ***\n', fail);
end
printf ('\n');
if fail > 0
  error ('test_cross_validate: %d group(s) failed', fail);
end
